name: Lint & Unit test

"on":
  workflow_call:
    inputs:
      gems:
        required: false
        type: string
        default: ""
      platform:
        required: false
        type: string
        default: "ubuntu-latest"
      chef_workstation_version:
        required: false
        type: string
        default: "latest"

jobs:
  rspec:
    # Some RSpec tests require a Windows environment
    runs-on: ${{ inputs.platform }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
        with:
          version: ${{ inputs.chef_workstation_version }}
      - name: Install Gems
        run: chef gem install -N "${{ inputs.gems }}"
        if: ${{ inputs.gems }}
        env:
          CHEF_LICENSE: accept-no-persist
      - name: Run RSpec
        run: chef exec rspec -f j -o tmp/rspec_results.json -f p
        env:
          CHEF_LICENSE: accept-no-persist
      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: tmp/rspec_results.json
        if: always()

  cookstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
        with:
          version: ${{ inputs.chef_workstation_version }}
      - name: Run Cookstyle
        run: chef exec cookstyle --display-cop-names --extra-details
        env:
          CHEF_LICENSE: accept-no-persist

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

