---
name: Push Policyfile to Chef Server
on:
  workflow_call:
    inputs:
      policy_group:
        required: false
        type: string
        default: "dev"
        description: "The policy group to push to (dev, stage, prod)"

jobs:
  push_policy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install Chef Workstation
        uses: actionshub/chef-install@5.0.2
        with:
          version: latest

      - name: Generate Policyfile.lock.json
        run: chef install
        env:
          CHEF_LICENSE: accept-no-persist

      - name: Write Chef config
        run: |
          echo "${{ secrets.CHEF_CI_PEM }}" | tr -d '\r' > key.pem
          
          cat > .chef_config <<EOF
          chef_server_url   "${{ vars.DEVOPS_CHEF_SERVER_ORG_URL }}"
          node_name         "${{ vars.DEVOPS_CICD_USER }}"
          client_key        "key.pem"
          EOF

      - name: Push Policyfile
        run: |
          echo "Pushing policy lock file to ${{ vars.DEVOPS_CHEF_SERVER_ORG_URL }}..."
          chef push ${{ inputs.policy_group }} Policyfile.lock.json --config .chef_config
        env:
          CHEF_LICENSE: accept-no-persist

      - name: Cleanup
        if: always()
        run: rm -f key.pem .chef_config
