---
name: Push Policyfile to Chef Server
on:
  workflow_call:
    inputs:
      policy_name:
        required: false
        type: string
        default: "dev"
        description: "The policy group to push to (dev, stage, prod)"

jobs:
  push_policy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Chef Workstation
        uses: actionshub/chef-install@3.0.0
        with:
          version: latest

      - name: Generate Policyfile.lock.json
        run: chef install
        env:
          CHEF_LICENSE: accept-no-persist

      - name: Write Chef config
        run: |
          echo "${{ secrets.CHEF_CI_PEM }}" | tr -d '\r' > "$CICD_PEM"
          
          cat > .chef_config <<EOF
          chef_server_url   "${{ vars.DEVOPS_CHEF_SERVER_ORG_URL }}"
          node_name         "${{ vars.DEVOPS_CICD_USER }}"
          client_key        "${CICD_PEM}"
          EOF

      - name: Push Policyfile
        run: |
          echo "Pushing policy lock file to ${{ vars.DEVOPS_CHEF_SERVER_ORG_URL }}..."
          chef push ${{ inputs.policy_name }} Policyfile.lock.json --config .chef_config
        env:
          CHEF_LICENSE: accept-no-persist

      - name: Cleanup
        if: always()
        run: rm -f key.pem .chef_config